-- =====================================================
-- SECTION 1: EXECUTIVE KPI OVERVIEW
-- Core business metrics used to measure overall performance.
-- =====================================================

-- Total revenue generated across all sales

SELECT ROUND(SUM(sales),2) AS total_revenue FROM sales;

-- Total profit generated across all sales

SELECT ROUND(SUM(profit),2) AS total_profit FROM sales;

-- Total number of unique orders placed

SELECT COUNT(DISTINCT order_id) AS total_orders FROM sales;

-- Average revenue generated per order

SELECT ROUND(SUM(sales) / COUNT(DISTINCT order_id) ,2) AS average_order_value FROM sales;

-- Total number of unique customers

SELECT COUNT(DISTINCT customer_id) AS total_customers FROM sales;

-- Total number of unique products sold

SELECT COUNT(DISTINCT product_id) AS total_products FROM sales;


-- =====================================================
-- SECTION 2: SALES PERFORMANCE ANALYSIS
-- Analyze revenue and profit across major business dimensions.
-- =====================================================

-- Revenue generated by each product category

SELECT category, ROUND(SUM(sales),2) AS revenue FROM sales GROUP BY category ORDER BY revenue DESC;

-- Profit generated by each product category

SELECT category, ROUND(SUM(profit),2) AS profit FROM sales GROUP BY category ORDER BY profit DESC;

-- Revenue generated by each customer segment

SELECT segment, ROUND(SUM(sales),2) AS revenue FROM sales GROUP BY segment ORDER BY revenue DESC;

-- Profit generated by each customer segment

SELECT segment, ROUND(SUM(profit),2) AS profit FROM sales GROUP BY segment ORDER BY profit DESC;

-- Revenue generated by each geographic region

SELECT region, ROUND(SUM(sales),2) AS revenue FROM sales GROUP BY region ORDER BY revenue DESC;

-- Profit generated by each geographic region

SELECT region, ROUND(SUM(profit),2) AS profit FROM sales GROUP BY region ORDER BY profit DESC;

-- Monthly revenue trend over time

SELECT DATE_TRUNC('month',order_date) AS month, ROUND(SUM(sales), 2) revenue FROM sales GROUP BY month ORDER BY month;


-- =====================================================
-- SECTION 3: CONTRIBUTION & PERCENTAGE ANALYSIS
-- Analyze how much each category, segment, region, customer,
-- or product contributes to overall business performance.
-- =====================================================

-- Revenue contribution percentage by product category

WITH total AS(SELECT SUM(sales) total_sales FROM sales) SELECT category, ROUND(SUM(sales),2) revenue, ROUND(SUM(sales)*100.0/MAX(total_sales), 2) revenue_share_pct FROM sales CROSS JOIN total GROUP BY category ORDER BY revenue DESC;

-- Revenue contribution percentage by customer segment

WITH total AS(SELECT SUM(sales) total_sales FROM sales) SELECT segment, ROUND(SUM(sales),2) revenue, ROUND(SUM(sales)*100.0/MAX(total_sales), 2) revenue_share_pct FROM sales CROSS JOIN total GROUP BY segment ORDER BY revenue DESC;

-- Revenue contribution percentage by region

WITH total AS(SELECT SUM(sales) total_sales FROM sales) SELECT region, ROUND(SUM(sales),2) revenue, ROUND(SUM(sales)*100.0/MAX(total_sales),2) revenue_share_pct FROM sales CROSS JOIN total GROUP BY region ORDER BY revenue DESC;

-- Profit contribution percentage by product category

WITH total AS (SELECT SUM(profit) total_profit FROM sales) SELECT category, ROUND(SUM(profit),2) profit, ROUND(SUM(profit)*100.0/MAX(total_profit),2) profit_share_pct FROM sales CROSS JOIN total GROUP BY category ORDER BY profit DESC;

-- Profit contribution percentage by customer segment

WITH total AS (SELECT SUM(profit) total_profit FROM sales) SELECT segment, ROUND(SUM(profit),2) profit, ROUND(SUM(profit)*100.0/MAX(total_profit),2) profit_share_pct FROM sales CROSS JOIN total GROUP BY segment ORDER BY profit DESC;

-- Profit contribution percentage by region

WITH total AS (SELECT SUM(profit) total_profit FROM sales) SELECT region, ROUND(SUM(profit),2) profit, ROUND(SUM(profit)*100.0/MAX(total_profit),2) profit_share_pct FROM sales CROSS JOIN total GROUP BY region ORDER BY profit DESC;

-- Revenue contribution percentage for each customer

SELECT customer_name, ROUND(SUM(sales), 2) revenue, ROUND(SUM(sales)*100.0/SUM(SUM(sales)) OVER(),2) revenue_pct FROM sales GROUP BY customer_name ORDER BY revenue DESC;

-- Revenue contribution percentage generated by the top 20 customers

WITH customer_sales AS (SELECT customer_name, SUM(sales) revenue  FROM sales GROUP BY customer_name), top20 AS (SELECT * FROM customer_sales ORDER BY revenue DESC LIMIT 20) SELECT ROUND(SUM(revenue)*100.0/(SELECT SUM(sales) FROM sales),2) contribution_pct FROM top20;

-- Revenue contribution percentage for each product

WITH product_sales AS (SELECT product_name, SUM(sales) revenue FROM sales GROUP BY product_name) SELECT product_name, revenue, ROUND(revenue*100.0/SUM(revenue) OVER(),2) revenue_pct FROM product_sales ORDER BY revenue DESC;

-- Revenue contribution percentage by category using window functions

SELECT category, ROUND(SUM(sales)*100.0/ SUM(SUM(sales)) OVER(), 2) contribution_pct FROM sales GROUP BY category;

-- Month-over-month revenue growth percentage

WITH monthly_sales AS (SELECT DATE_TRUNC('month',order_date) AS month, SUM (sales) revenue FROM sales GROUP BY month) SELECT month, revenue, ROUND((revenue - LAG(revenue) OVER(ORDER BY month))*100.0/ LAG(revenue) OVER(ORDER BY month),2) growth_pct FROM monthly_sales;

-- Month-over-month profit growth percentage

WITH monthly_profit AS (SELECT DATE_TRUNC('month',order_date) AS month, SUM (profit) profit FROM sales GROUP BY month) SELECT month, profit, ROUND((profit - LAG(profit) OVER(ORDER BY month))*100.0/ LAG(profit) OVER(ORDER BY month),2) growth_pct FROM monthly_profit;

-- Overall company profit margin percentage

SELECT ROUND(SUM(profit)*100.0/ SUM(sales), 2) profit_margin_pct FROM sales;

-- Profit margin percentage by region

SELECT region, ROUND(SUM(profit)*100.0/ SUM(sales), 2) profit_margin_pct FROM sales GROUP BY region ORDER BY profit_margin_pct DESC;

-- Profit margin percentage by category

SELECT category, ROUND(SUM(profit)*100.0/ SUM(sales), 2) profit_margin_pct FROM sales GROUP BY category ORDER BY profit_margin_pct DESC;

-- Profit margin percentage by customer segment

SELECT segment, ROUND(SUM(profit)*100.0/ SUM(sales), 2) profit_margin_pct FROM sales GROUP BY segment ORDER BY profit_margin_pct DESC;

-- =====================================================
-- SECTION 4: CUSTOMER & PRODUCT SEGMENTATION
-- Analyze customer value, product performance,
-- ranking, and business-defined tiers.
-- =====================================================

-- Rank all products by total revenue generated

SELECT product_name, SUM(sales) revenue, ROW_NUMBER() OVER(ORDER BY SUM(sales) DESC) rank FROM sales GROUP BY product_name;

-- Top 10 products by revenue

WITH product_sales AS (SELECT product_name, SUM(sales) revenue FROM sales GROUP BY product_name) SELECT * FROM product_sales ORDER BY revenue DESC LIMIT 10;

-- Top 10 customers by revenue

SELECT customer_name, SUM(sales) revenue FROM sales GROUP BY customer_name ORDER BY revenue DESC LIMIT 10;

-- Rank products with the lowest revenue

SELECT product_name, SUM(sales) revenue, ROW_NUMBER() OVER(ORDER BY SUM(sales) ASC) rank FROM sales GROUP BY product_name LIMIT 10;

-- Rank products with the highest profit

SELECT product_name, SUM(profit) profit, ROW_NUMBER() OVER(ORDER BY SUM(profit) DESC) rank FROM sales GROUP BY product_name LIMIT 10;

-- Top 10 least profitable products using dense ranking

SELECT product_name, profit, ranking FROM (SELECT product_name, SUM(profit) AS profit, DENSE_RANK() OVER(ORDER BY SUM(profit) ASC) AS ranking  FROM sales GROUP BY product_name) AS ranking_products WHERE ranking <= 10;

-- Categorize products based on profit generated

SELECT product_name, profit, CASE WHEN profit > 500 THEN 'High Profit' WHEN profit > 100 THEN 'Medium Profit' ELSE 'Low Profit' END profit_tier FROM sales ORDER BY profit DESC;

-- Categorize customers into business value tiers

SELECT customer_name, SUM(sales) revenue, CASE WHEN SUM(sales) > 10000 THEN 'VIP' WHEN SUM(sales) > 5000 THEN 'Premium' ELSE 'Standard' END customer_tier FROM sales GROUP BY customer_name ORDER BY revenue DESC;

-- Revenue contribution of each customer tier

SELECT customer_tier, COUNT(*) AS total_customers, SUM(revenue) AS tier_total_revenue FROM (SELECT customer_name, SUM(sales) AS revenue, CASE WHEN SUM(sales) > 10000 THEN 'VIP' WHEN SUM(sales) > 5000 THEN 'Premium' ELSE 'Standard' END AS customer_tier FROM sales GROUP BY customer_name) AS customer_segments GROUP BY customer_tier ORDER BY tier_total_revenue DESC;

-- Categorize products into revenue tiers

SELECT product_name, SUM(sales) revenue, CASE WHEN SUM(sales) > 10000 THEN 'Star' WHEN SUM(sales) > 5000 THEN 'Strong' ELSE 'Regular' END product_tier FROM sales GROUP BY product_name ORDER BY revenue DESC;


-- =====================================================
-- SECTION 5: ADVANCED ANALYTICAL TECHNIQUES
-- Demonstrate window functions, cumulative metrics,
-- and trend analysis techniques.
-- =====================================================

-- Running cumulative revenue over time

SELECT order_date, sales, SUM(sales) OVER(ORDER BY order_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_revenue FROM sales;

-- Cumulative monthly revenue trend

WITH monthly_sales AS (SELECT DATE_TRUNC('month', order_date) AS month, SUM(sales) revenue FROM sales GROUP BY month) SELECT month, revenue, SUM(revenue) OVER(ORDER BY month) cumulative_revenue FROM monthly_sales;

-- Three-month moving average revenue trend

WITH monthly_sales AS (SELECT DATE_TRUNC('month', order_date) AS month, SUM(sales) revenue FROM sales GROUP BY month) SELECT month, revenue, ROUND(AVG(revenue) OVER(ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) moving_avg FROM monthly_sales;

-- =====================================================
-- SECTION 6: BUSINESS DECISION SUPPORT QUESTIONS
-- Answer stakeholder-focused questions using insights
-- generated from previous analysis.
-- =====================================================

-- Which product category generates the most revenue?

SELECT category, SUM(sales) revenue FROM sales GROUP BY category ORDER BY revenue DESC LIMIT 1;

-- Which region has the highest profit margin?

SELECT region, ROUND(SUM(profit)*100.0/SUM(sales),2) profit_margin_pct FROM sales GROUP BY region ORDER BY profit_margin_pct LIMIT 1;

-- What are the top 10 products by revenue?

SELECT product_name, SUM(sales) revenue FROM sales GROUP BY product_name ORDER BY revenue DESC LIMIT 10;

-- Which months underperform compared to the average month?

WITH monthly_sales AS (SELECT DATE_TRUNC('month',order_date) AS month, SUM(sales) revenue FROM sales GROUP BY month), avg_sales AS (SELECT AVG(revenue) avg_revenue FROM monthly_sales) SELECT month, revenue FROM monthly_sales CROSS JOIN avg_sales WHERE revenue < avg_revenue ORDER BY revenue;

-- Which customer segment places the most orders?

SELECT segment, COUNT(DISTINCT order_id) orders FROM sales GROUP BY segment ORDER BY orders DESC;

-- Who are the top 20 customers by revenue?

SELECT customer_name, SUM(sales) revenue FROM sales GROUP BY customer_name ORDER BY revenue DESC LIMIT 20;

-- Which products are generating losses?

SELECT product_name, SUM(profit) total_profit FROM sales GROUP BY product_name HAVING SUM(profit) < 0 ORDER BY total_profit;